baseURL = 'https://gianhiltbrunner.ch/'
languageCode = 'en-us'
title = 'Gian Hiltbrunner'
theme = 'archie'
copyright = "© Gian Hiltbrunner"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[pagination]
pagerSize = 3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "A Curious Engineer's Journey Through Data, Code, and Culinary Experiments"
	favicon = "/favicon.svg" # path to favicon
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
	customCSS = ["css/books.css", "css/mermaid.css"] # custom CSS files
	customJS = [
		"https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js",
		"<script>mermaid.initialize({ startOnLoad: true, theme: 'default' });</script>"
	]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/gianhiltbrunner"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/gianhiltbrunner"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2


[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Books"
url = "/books"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5